pubmed:
  lr: 0.001
  l2_coef: 0.001
  patience: 100


actor:
  lr: 0.001
  l2_coef: 0.00001
  patience: 100


chameleonf:
  lr: 0.001
  l2_coef: 0.001
  patience: 100


squirrelf:
  lr: 0.001
  l2_coef: 0.00005
  patience: 100


romanempire:
  lr: 0.001
  l2_coef: 0.001
  patience: 100


amazonratings:
  lr: 0.001
  l2_coef: 0.001
  patience: 100


blogcatalog:
  lr: 0.001
  l2_coef: 0.00001
  patience: 100


flickr:
  lr: 0.001
  l2_coef: 0.
  patience: 100


photo:
  lr: 0.001
  l2_coef: 0.
  patience: 100


wikics:
  lr: 0.005
  l2_coef: 0.00001
  patience: 100
